# -*- restclient -*-

:account_id = c994f7b4-124c-4ff5-a49b-397564cca58a

#Add new account
POST http://localhost:3000/accounts
Content-type: application/json
{"opening_balance": 100}

#Credit account
POST http://localhost:3000/accounts/:account_id/credit
Content-type: application/json
{"amount": 10}

#Debit account
POST http://localhost:3000/accounts/:account_id/debit
Content-type: application/json
{"amount": 5}

#Local
GET http://localhost:3000/accounts/:account_id/summary

