# -*- restclient -*-

:account_id = 00d7d381-473a-48c5-b28c-3584b2ad7b47

#Add new account
POST http://localhost:3000/accounts
Content-type: application/json
{"opening_balance": 100}

#Credit account
POST http://localhost:3000/accounts/:account_id/credit
Content-type: application/json
{"amount": 10}

#Debit account
POST http://localhost:3000/accounts/:account_id/debit
Content-type: application/json
{"amount": 5}

#Summary
GET http://localhost:3000/accounts/:account_id/summary

#Event feed
GET http://localhost:3000/events

#Event
GET http://localhost:3000/events/9b8fb800-0a6d-4132-88b9-bc31368aa9ac

