# -*- restclient -*-

:account_id = 5a5a5105-6fb8-488a-a02b-b24077cb8d9e

#Add new account
POST http://localhost:3000/accounts
Content-type: application/json
{"opening_balance": 100}

#Credit account
POST http://localhost:3000/accounts/:account_id/credit
Content-type: application/json
{"amount": 10}

#Debit account
POST http://localhost:3000/accounts/:account_id/debit
Content-type: application/json
{"amount": 5}

#Summary
GET http://localhost:3000/accounts/:account_id/summary

#Event feed
GET http://localhost:3000/events

#Event
GET http://localhost:3000/events/6e65bd79-26d5-47ef-861b-82197c97df24


#Get event
GET http://localhost:3000/events/a87b5df1-f767-48a3-8fed-71558c142ea9
